spring.application.name=BETQ
server.address=0.0.0.0
server.port=8080
server.tomcat.connection-timeout=2000000
spring.main.lazy-initialization=false

# -------------------------------
# SQL SERVER CONFIG
# -------------------------------
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BETQ;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# -------------------------------
# JPA CONFIG
# -------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

jwt.secret=6-e73lu414DWrTkFqsWylijqFft1c0mJxneReCg0Sgq-JYKA6fQ52pwMDl8AEKvVHUxoN5ZFALOVTZPLAm0F7A
jwt.access-expire=900000
jwt.refresh-expire=86400000